### ISSUE TITLE
Poruri Sai Rahul: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by rahulporuri** [LSST-nonproject/sims_maf_viz#1]
<p><br><blockquote>This issue was created by @rahulporuri via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by rhiannonlynne** [comment]
Hi Rahul, Thanks for signing up as a volunteer. Can you tell me a bit about what you wanted to work on with this project and if there is anything I can do to help?

**Comment by rahulporuri** [comment]
@rhiannonlynne hey, I've been interested in contributing to open source projects, specifically those related to astronomy but I am in need of guidance. And I thought this was a good opportunity so I volunteered. If you have the time, I would like to talk to you so that you can understand what level of understanding I'm at and in which way I can contribute. I'm sorry if this is not what was expected of volunteers. And sorry for the extremely late reply.
